### PR TITLE
Update use of cml cli

### PR DESCRIPTION
**Pull request by tasdomas**

### CODE REVIEW

**Review by 0x2b3bfa0 — APPROVED** [review]

**Comment by shcheklein** [comment]
@tasdomas @0x2b3bfa0 this repo is auto-generated (to make history exactly the way we want, every commit matters, we don't want to have extra commits), please make a PR here https://github.com/iterative/example-repos-dev/blob/master/example-get-started/generate.sh and we need to force push after that to cleanup the repo.

**Comment by 0x2b3bfa0** [comment]
Thanks, @shcheklein! 🙈 I forgot it was a generic example repository.

**Comment by tasdomas** [comment]
Thanks @shcheklein   - I wasn't aware that the repo was generated

**Comment by shcheklein** [comment]
@tasdomas @0x2b3bfa0 no worries at all folks, it's not p0 or something, but it's better to fix it in some reasonable timeline. And we should probably disable any PR merging in this repo.

**Pull request merged**
