### PR TITLE
Add PyYAML to src/requirements.txt

### PR DESCRIPTION
**Pull request by treszkai**
The example code 

```
$ dvc run -n prepare \
          -p prepare.seed,prepare.split \
          -d src/prepare.py -d data/data.xml \
          -o data/prepared \
          python src/prepare.py data/data.xml
```

on https://dvc.org/doc/start/data-pipelines fails otherwise.

### CODE REVIEW

**Comment by shcheklein** [comment]
@treszkai could you please share the error you are getting?

**Comment by shcheklein** [comment]
Reproduced this. Thanks, fixing in the repo that generates this one.

**Comment by shcheklein** [comment]
Fixed. But now we need to update all md5 hashes across docs - we should support some variables for the docs to simplify the updates - @jorgeorpinel @rogermparent

**Comment by jorgeorpinel** [comment]
Its a good idea but do we have another use case other than hash values? a) its a perfects case for grep replace b) I don't worry to much about outdated md5s in docs (as long as they're consistent within each doc or example), tbh (maybe I should).

**Comment by shcheklein** [comment]
@jorgeorpinel agreed, it's not critical for majority of the docs. I'm concerned about get started a bit. grep can do that, but not that easy since we have changed md5s across different commits.

**Comment by jorgeorpinel** [comment]
Checked GS and md5 use seems consistent. Theres just `a304afb` for `data/data.xml` in a few of the pages, and a few other ones that are only mentioned once each.

**Comment by victormico** [comment]
In the current [requirements file](https://github.com/iterative/example-get-started/blame/06ea48980a34ef57041c9b905cafcb40d9c3ddbc/src/requirements.txt#L3) the library is `pyaml` instead of `pyyaml`.

**Pull request closed without merging**
